#на клиентах надо поставить docker-socket-proxy (тут есть docker-compose)
---
services:
  wud:
    image: getwud/wud:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/wud/store:/store:rw
    ports:
      - "3030:3000"
    environment:
      - WUD_BASE_URL=http://localhost:3000

      # Локальный watcher
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_LOCAL_CRON=0 * * * *

      # Удаленный watcher - используйте URL вместо HOST+PORT
      - WUD_WATCHER_n8n_HOST=172.16.0.40
      - WUD_WATCHER_n8n_PORT=2375
      - WUD_WATCHER_n8n_WATCHALL=true
      - WUD_WATCHER_n8n_CRON=0 * * * *
      # Удаленный watcher - используйте URL вместо HOST+PORT
      - WUD_WATCHER_mattermost_HOST=172.16.0.39
      - WUD_WATCHER_mattermost_PORT=2375
      - WUD_WATCHER_mattermost_WATCHALL=true
      - WUD_WATCHER_mattermost_CRON=0 * * * *
      # Удаленный watcher - используйте URL вместо HOST+PORT
      - WUD_WATCHER_docmost_HOST=172.16.0.37
      - WUD_WATCHER_docmost_PORT=2375
      - WUD_WATCHER_docmost_WATCHALL=true
      - WUD_WATCHER_docmost_CRON=0 * * * *
