#sudo mkdir -p /opt/moodle/moodledata
#sudo chmod -R 777 /opt/moodle/moodledata
#docker compose up -d --build
#после настройки и запуска. добавить русский язык 
#unzip ru.zip -d /opt/moodle/moodledata/lang/
#sudo chown -R 33:33 /opt/moodle/moodledata/lang
#sudo chmod -R 755 /opt/moodle/moodledata/lang
services:
  mariadb:
    image: mariadb:10.11
    container_name: moodle_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /opt/moodle/moodle_db_data:/var/lib/mysql
#    networks:
#      - moodle_network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --wait_timeout=28800
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  moodle:
    build: .
    container_name: moodle_app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "80"
    environment:
      - MOODLE_DB_HOST=${MOODLE_DB_HOST}
      - MOODLE_DB_NAME=${MOODLE_DB_NAME}
      - MOODLE_DB_USER=${MOODLE_DB_USER}
      - MOODLE_DB_PASSWORD=${MOODLE_DB_PASSWORD}
      - MOODLE_WWWROOT=${MOODLE_WWWROOT}
      - MOODLE_DATAROOT=${MOODLE_DATAROOT}
    volumes:
      - /opt/moodle/moodledata:/var/www/moodledata
#    networks:
#      - moodle_network

  nginx:
    image: nginx:alpine
    container_name: moodle_nginx
    restart: unless-stopped
    depends_on:
      - moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/moodle/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/moodle/nginx/ssl:/etc/nginx/ssl:ro
      - /opt/moodle/nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd
      - /opt/moodle/nginx/config.d:/etc/nginx/conf.d/
      - /opt/moodle/nginx/sites-available:/etc/nginx/sites-available/
      - /opt/moodle/nginx/sites-enabled:/etc/nginx/sites-enabled/
#    networks:
#      - moodle_network

#networks:
#  moodle_network:
#    driver: bridge
